#!/usr/bin/env python
import sys
import unittest

from tests import all_tests


if __name__ == '__main__':
    if '-v' in sys.argv:
        import logging
        logging.basicConfig(level=logging.DEBUG)
    tests = all_tests()
    results = unittest.TextTestRunner().run(tests)
