#!/usr/bin/env python
import logging
import optparse
import sys
import unittest

from smarkets import __version__
from tests import all_tests


if __name__ == '__main__':
    version = "%%prog %s" % __version__
    parser = optparse.OptionParser(version=version)
    parser.add_option(
        '-v', '--verbose', dest='verbose', action='store_true',
        default=False, help="turn on DEBUG logging level")
    parser.add_option(
        '-f', '--file', dest='password_filename',
        help="read usernames and passwords from FILE",
        metavar='FILE')
    parser.add_option(
        '-m', '--markets', dest='market_filename',
        help="read markets from FILE",
        metavar='FILE')
    parser.add_option(
        '-s', '--server', dest='server',
        help="server host to connect to",
        metavar='SERVER')
    parser.add_option(
        '-p', '--port', dest='port',
        help="server port to connect to",
        metavar='PORT')
    parser.add_option(
        '-k', '--skip-online', dest='skip_online', action='store_true',
        default=False, help="skip online tests")
    options, args = parser.parse_args()
    level = logging.WARNING
    if options.verbose:
        level = logging.DEBUG
    logging.basicConfig(level=level)
    kwargs = {}
    for name in (
        'password_filename',
        'market_filename',
        'server',
        'port',
        'skip_online',
        ):
        val = getattr(options, name)
        if val:
            kwargs[name] = val
    tests = all_tests(**kwargs)
    results = unittest.TextTestRunner().run(tests)
